services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    env_file:
      - environments/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 20s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgres

  backup:
    image: ghcr.io/hadrylouis/docker-db-backup:latest
    container_name: backup
    env_file:
      - environments/backup.env
    restart: always