export AWS_ACCESS_KEY_ID=${DEFAULT_S3_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${DEFAULT_S3_KEY_SECRET}
export AWS_DEFAULT_REGION=${DEFAULT_S3_REGION}
export PARAMS_AWS_ENDPOINT_URL=" --endpoint-url ${DEFAULT_S3_PROTOCOL}://${DEFAULT_S3_HOST}"
export SOURCE_FILE="pgsql_.*\.sql.zst$"
export LATEST_FILE=$(aws s3 ls s3://${DEFAULT_S3_BUCKET}/${DEFAULT_S3_PATH}/ ${PARAMS_AWS_ENDPOINT_URL} --recursive | grep -E ${SOURCE_FILE} | sort -r | head -n 1 | awk '{print $4}')
export TEMP_PATH="/tmp"

aws s3 cp s3://${DEFAULT_S3_BUCKET}/${LATEST_FILE} ${TEMP_PATH}/${LATEST_FILE} ${PARAMS_AWS_ENDPOINT_URL}

restore ${TEMP_PATH}/${LATEST_FILE} ${DB01_TYPE} ${DB01_HOST} ${DB01_NAME} ${DB01_USER} ${DB01_PASS} ${DB01_PORT}